/** 캐릭터 세트 데이터 (Python persona_data.py 이식) */

export const CHARACTER_SETS = [
  {
    id: 'pokemon',
    name_kr: '포켓몬',
    name_en: 'Pokémon',
    description_kr: '16종 포켓몬과 매칭되는 MBTI 성격 테스트입니다.',
    description_en: 'MBTI personality test matching 16 Pokémon characters.',
    character_count: 16,
  },
  {
    id: 'digimon',
    name_kr: '디지몬',
    name_en: 'Digimon',
    description_kr: '디지몬 어드벤처의 16종 디지몬과 매칭되는 MBTI 성격 테스트입니다.',
    description_en: 'MBTI personality test matching 16 Digimon from Digimon Adventure.',
    character_count: 16,
  },
  {
    id: 'kakao_friends',
    name_kr: '카카오프렌즈',
    name_en: 'Kakao Friends',
    description_kr: '카카오프렌즈 16개 캐릭터와 매칭되는 MBTI 성격 테스트입니다.',
    description_en: 'MBTI personality test matching 16 Kakao Friends characters.',
    character_count: 16,
  },
];

const POKEMON_CHARACTERS = {
  ISTJ: { id: 'blastoise', name_kr: '거북왕', name_en: 'Blastoise', mbti_type: 'ISTJ', image_path: 'character_images/pokemon/blastoise.png', description_kr: '성실하게 단계를 밟아 완성된 믿음직한 포켓몬입니다. 두터운 등껍질과 정밀한 캐논처럼 원칙과 체계를 중시하며 맡은 바를 끝까지 완수합니다.', description_en: 'A reliable Pokémon forged through steady, disciplined growth. Like its sturdy shell and precise cannons, it values principles and systems, always seeing its duties through to the end.' },
  ISFJ: { id: 'bulbasaur', name_kr: '이상해씨', name_en: 'Bulbasaur', mbti_type: 'ISFJ', image_path: 'character_images/pokemon/bulbasaur.png', description_kr: '조용하지만 책임감이 누구보다 강한 포켓몬입니다. 무리를 묵묵히 지키고 갈등을 중재하는 헌신적인 수호자로, 자신보다 동료를 먼저 생각합니다.', description_en: 'A quietly responsible Pokémon stronger in duty than anyone. Acts as a devoted guardian, mediating conflicts and always putting companions before itself.' },
  INFJ: { id: 'mew', name_kr: '뮤', name_en: 'Mew', mbti_type: 'INFJ', image_path: 'character_images/pokemon/mew.png', description_kr: '모든 포켓몬의 시조로 전해지는 신비로운 존재입니다. 좀처럼 모습을 드러내지 않지만, 장난기 어린 외면 뒤에 세계를 꿰뚫는 깊은 통찰을 품고 있습니다.', description_en: 'A mythical being said to be the ancestor of all Pokémon. Rarely shows itself, but beneath a playful exterior lies a profound insight that sees through the world.' },
  INTJ: { id: 'mewtwo', name_kr: '뮤츠', name_en: 'Mewtwo', mbti_type: 'INTJ', image_path: 'character_images/pokemon/mewtwo.png', description_kr: '냉철한 지능과 강한 독립 의지를 가진 포켓몬입니다. 인간도 신도 따르지 않으며, 자신의 존재 의미를 끊임없이 탐구하고 장기적 전략으로 목표를 이루어냅니다.', description_en: 'A Pokémon of cold intelligence and fierce independence. Refuses to bow to humans or gods, relentlessly questioning its own existence while pursuing goals through long-term strategy.' },
  ISTP: { id: 'charizard', name_kr: '리자몽', name_en: 'Charizard', mbti_type: 'ISTP', image_path: 'character_images/pokemon/charizard.png', description_kr: '독립적이고 자존심 강한 장인 포켓몬입니다. 명령보다 실력을 우선하며, 진심으로 인정하는 상대에게만 따릅니다. 강한 적 앞에서 폭발적인 본능으로 진가를 발휘합니다.', description_en: 'An independent and proud craftsman Pokémon. Prioritizes skill over orders, and only follows those it genuinely respects. Shows its true power with explosive instinct against strong opponents.' },
  ISFP: { id: 'snorlax', name_kr: '잠만보', name_en: 'Snorlax', mbti_type: 'ISFP', image_path: 'character_images/pokemon/snorlax.png', description_kr: '현재의 즐거움에 가장 충실한 포켓몬입니다. 먹고 자는 감각적 삶을 즐기며 주변에 온화한 편안함을 줍니다. 자신의 페이스를 무엇보다 소중히 여깁니다.', description_en: 'A Pokémon most devoted to the pleasures of the present moment. Enjoys a sensory life of eating and sleeping, radiating gentle comfort to those around it. Treasures its own rhythm above all.' },
  INFP: { id: 'ditto', name_kr: '메타몽', name_en: 'Ditto', mbti_type: 'INFP', image_path: 'character_images/pokemon/ditto.png', description_kr: '상대의 모습으로 변신해 공감과 조화를 이루는 포켓몬입니다. 본모습을 고집하지 않는 유연한 자아 뒤에 무한한 가능성과 따뜻한 이상주의를 품고 있습니다.', description_en: 'A Pokémon that transforms into others to achieve empathy and harmony. Behind its flexible self that never clings to one form lies infinite potential and warm idealism.' },
  INTP: { id: 'porygon', name_kr: '폴리곤', name_en: 'Porygon', mbti_type: 'INTP', image_path: 'character_images/pokemon/porygon.png', description_kr: '인간이 프로그래밍으로 만들어낸 데이터 생명체입니다. 감정적 교류보다 정보와 논리로 세상을 이해하며, 데이터를 분석하고 오류를 탐지하는 것 자체를 삶의 목적으로 삼습니다.', description_en: 'A digital life-form created through human programming. Understands the world through information and logic rather than emotional exchange, making data analysis and error detection its very purpose.' },
  ESTP: { id: 'squirtle', name_kr: '꼬부기', name_en: 'Squirtle', mbti_type: 'ESTP', image_path: 'character_images/pokemon/squirtle.png', description_kr: '꼬부기단 대장으로 재치와 실행력을 겸비한 포켓몬입니다. 위기 상황에서 몸을 사리지 않고 뛰어들며, 이론보다 현장에서 직접 부딪치는 과감한 모험을 즐깁니다.', description_en: 'Leader of the Squirtle Squad, combining wit with decisive action. Never hesitates to leap into danger, preferring bold on-the-spot adventure over theory.' },
  ESFP: { id: 'pikachu', name_kr: '피카츄', name_en: 'Pikachu', mbti_type: 'ESFP', image_path: 'character_images/pokemon/pikachu.png', description_kr: '언제 어디서나 주인공이 되는 타고난 스타 포켓몬입니다. 넘치는 에너지와 풍부한 감정 표현으로 주변 분위기를 환하게 밝히며, 소중한 이와의 유대를 무엇보다 소중히 여깁니다.', description_en: 'A born star that becomes the main character wherever it goes. Lights up any atmosphere with overflowing energy and emotional expressiveness, cherishing bonds with loved ones above all.' },
  ENFP: { id: 'eevee', name_kr: '이브이', name_en: 'Eevee', mbti_type: 'ENFP', image_path: 'character_images/pokemon/eevee.png', description_kr: '8가지 진화 가능성을 가진 무한 잠재력의 포켓몬입니다. \'나는 무엇이든 될 수 있다\'는 열린 가능성 그 자체로, 새로운 환경에 빠르게 적응하고 매번 새로운 꿈을 향해 나아갑니다.', description_en: 'A Pokémon of infinite potential with 8 possible evolutions. The embodiment of open possibility — \'I can become anything\' — quickly adapting to new environments and always chasing new dreams.' },
  ENTP: { id: 'meowth', name_kr: '나옹', name_en: 'Meowth', mbti_type: 'ENTP', image_path: 'character_images/pokemon/meowth.png', description_kr: '로켓단의 브레인이자 말솜씨가 화려한 포켓몬입니다. 기발한 발명과 계략으로 상황을 뒤집으며, 고정관념을 깨는 아이디어로 끊임없이 새로운 가능성을 탐색합니다.', description_en: 'The brains of Team Rocket with sharp, flashy rhetoric. Constantly overturns situations with inventive schemes, endlessly exploring new possibilities by breaking conventional thinking.' },
  ESTJ: { id: 'arcanine', name_kr: '윈디', name_en: 'Arcanine', mbti_type: 'ESTJ', image_path: 'character_images/pokemon/arcanine.png', description_kr: '경찰견의 대명사로 질서와 정의를 수호하는 포켓몬입니다. 위엄 있는 카리스마로 무리를 체계적으로 통솔하며, 충성과 규율을 최우선 가치로 삼습니다.', description_en: 'The iconic police dog Pokémon, guardian of order and justice. Leads its group systematically with dignified charisma, placing loyalty and discipline as its highest values.' },
  ESFJ: { id: 'charmander', name_kr: '파이리', name_en: 'Charmander', mbti_type: 'ESFJ', image_path: 'character_images/pokemon/charmander.png', description_kr: '주인과의 유대와 인정에 가장 민감한 포켓몬입니다. 따뜻한 감정 표현과 타인을 기쁘게 하려는 마음이 강하며, 함께하는 분위기 속에서 가장 빛을 발합니다.', description_en: 'A Pokémon most sensitive to bonds and recognition from its trainer. Strong in warm emotional expression and the desire to please others, it shines brightest in a harmonious, cooperative atmosphere.' },
  ENFJ: { id: 'dragonite', name_kr: '망나뇽', name_en: 'Dragonite', mbti_type: 'ENFJ', image_path: 'character_images/pokemon/dragonite.png', description_kr: '바다에서 조난된 이들을 구조하고 동료를 이끄는 따뜻한 리더 포켓몬입니다. 강대한 힘을 오직 타인을 위해 사용하며, 온화한 카리스마로 공동체를 하나로 화합시킵니다.', description_en: 'A warm leader Pokémon that rescues those lost at sea and guides its companions. Uses its immense power solely for others, uniting the community with gentle, inspiring charisma.' },
  ENTJ: { id: 'jigglypuff', name_kr: '푸린', name_en: 'Jigglypuff', mbti_type: 'ENTJ', image_path: 'character_images/pokemon/jigglypuff.png', description_kr: '모두가 자신의 노래를 들어야 한다는 확고한 목표의식을 가진 포켓몬입니다. 관객이 잠들어도 끝까지 노래하고 얼굴에 낙서해 존재감을 각인시키는 불굴의 추진력과 지배욕을 보여줍니다.', description_en: 'A Pokémon with an unyielding conviction that everyone must hear its song. Even if the audience falls asleep, it keeps singing and marks their faces — an iron-willed drive and dominance that refuses to be ignored.' },
};

const DIGIMON_CHARACTERS = {
  ISTJ: { id: 'gabumon', name_kr: '파피몬', name_en: 'Gabumon', mbti_type: 'ISTJ', image_path: 'character_images/digimon/gabumon.png', description_kr: '자신만의 선과 규칙이 명확한 믿음직한 디지몬입니다. 소중한 가죽처럼 원칙을 소중히 여기며, 무리를 이탈하려는 파트너를 묵묵히 기다려주고 곁을 지키는 성실한 수호자입니다.', description_en: 'A reliable Digimon with a clear sense of personal rules and principles. Treasures its values like its precious pelt, quietly waiting for its partner and staying loyal through every trial.' },
  ISFJ: { id: 'biyomon', name_kr: '피요몬', name_en: 'Biyomon', mbti_type: 'ISFJ', image_path: 'character_images/digimon/biyomon.png', description_kr: '파트너를 향한 사랑과 헌신이 넘치는 디지몬입니다. 집단의 화합을 중시하며 타인의 감정에 깊이 공감하고, 자신이 사랑하는 대상을 위해 기꺼이 자신을 낮추며 봉사합니다.', description_en: 'A Digimon overflowing with love and devotion for its partner. Values group harmony, empathizes deeply with others\' emotions, and willingly puts itself last to serve those it cares about.' },
  INFJ: { id: 'angemon', name_kr: '엔젤몬', name_en: 'Angemon', mbti_type: 'INFJ', image_path: 'character_images/digimon/angemon.png', description_kr: '절망적인 순간에 나타나 희망의 빛을 제시하는 이상주의적 디지몬입니다. 평소엔 온화하지만 악의 세력 앞에서는 신념을 위해 자신을 기꺼이 희생하는 숭고한 통찰자입니다.', description_en: 'An idealistic Digimon that appears in desperate moments to offer the light of hope. Normally gentle, but willing to sacrifice itself for its convictions when faced with evil.' },
  INTJ: { id: 'myotismon', name_kr: '묘티스몬', name_en: 'Myotismon', mbti_type: 'INTJ', image_path: 'character_images/digimon/myotismon.png', description_kr: '냉철한 지략과 장기적 계획으로 목표를 추구하는 디지몬입니다. 감정에 휘둘리지 않고 부하를 체계적으로 배치하며, 상대의 약점을 정확히 파고드는 용의주도한 전략가입니다.', description_en: 'A Digimon that pursues its goals through cold strategy and long-term planning. Unswayed by emotion, it systematically deploys subordinates and precisely exploits opponents\' weaknesses.' },
  ISTP: { id: 'wargreymon', name_kr: '워그레이몬', name_en: 'WarGreymon', mbti_type: 'ISTP', image_path: 'character_images/digimon/wargreymon.png', description_kr: '화려한 말 대신 압도적인 실력으로 증명하는 전설의 전사 디지몬입니다. 복잡한 이론보다 본능에 따라 실전에서 진가를 발휘하며, 위기 상황에서도 냉정하게 판단하고 승리를 쟁취합니다.', description_en: 'A legendary warrior Digimon that proves itself through overwhelming skill, not words. Trusts instinct over theory, showing its true value in real combat and calmly seizing victory even in crisis.' },
  ISFP: { id: 'gomamon', name_kr: '쉬라몬', name_en: 'Gomamon', mbti_type: 'ISFP', image_path: 'character_images/digimon/gomamon.png', description_kr: '낙천적이고 매 순간의 여유를 즐길 줄 아는 자유로운 영혼의 디지몬입니다. 고지식한 파트너 옆에서 농담을 던지며 분위기를 환기시키고, 물결에 몸을 맡기듯 유연하게 소소한 즐거움을 찾아냅니다.', description_en: 'A free-spirited Digimon who knows how to enjoy the moment. Lightens the mood with jokes beside its rigid partner, flowing flexibly like a current and always finding small joys along the way.' },
  INFP: { id: 'patamon', name_kr: '파닥몬', name_en: 'Patamon', mbti_type: 'INFP', image_path: 'character_images/digimon/patamon.png', description_kr: '여리고 순수한 외면 뒤에 거대한 성스러운 에너지를 품은 디지몬입니다. 평소엔 수줍고 조용하지만, 깊은 내면의 신념을 위해서라면 온 힘을 다해 싸우는 외유내강형 이상주의자입니다.', description_en: 'A Digimon that hides immense sacred energy behind a soft, innocent exterior. Usually shy and quiet, but fights with everything it has for deep inner convictions — the classic idealist with iron within.' },
  INTP: { id: 'tentomon', name_kr: '텐타몬', name_en: 'Tentomon', mbti_type: 'INTP', image_path: 'character_images/digimon/tentomon.png', description_kr: '해박한 지식과 논리적 분석을 즐기는 지식인 디지몬입니다. 상황을 객관적으로 분석하고 설명하는 것을 좋아하며, 새로운 정보와 원리에 무한한 호기심을 보이는 사색가입니다.', description_en: 'An intellectual Digimon that loves deep knowledge and logical analysis. Enjoys objectively analyzing and explaining situations, showing boundless curiosity for new information and principles.' },
  ESTP: { id: 'veemon', name_kr: '브이몬', name_en: 'Veemon', mbti_type: 'ESTP', image_path: 'character_images/digimon/veemon.png', description_kr: '고민보다 행동이 먼저 나가는 즉흥적인 모험가 디지몬입니다. 장난기 넘치고 스릴 넘치는 도전을 온몸으로 즐기며, 위험한 상황일수록 더욱 빛나는 에너지 넘치는 실행파입니다.', description_en: 'An impulsive adventurer Digimon whose body moves before it thinks. Loves thrill-filled challenges with every fiber of its being, shining brightest when danger is greatest.' },
  ESFP: { id: 'palmon', name_kr: '팔몬', name_en: 'Palmon', mbti_type: 'ESFP', image_path: 'character_images/digimon/palmon.png', description_kr: '자신의 외모를 가꾸는 것을 좋아하고 감정 표현이 매우 솔직한 디지몬입니다. 화려한 것을 동경하며 기쁨과 슬픔을 드라마틱하게 표현하는 활발하고 사교적인 자유로운 영혼입니다.', description_en: 'A Digimon who loves caring for its appearance and expresses emotions with striking honesty. Drawn to glamor and drama, it\'s a lively and sociable free spirit who wears every feeling on its sleeve.' },
  ENFP: { id: 'agumon', name_kr: '아구몬', name_en: 'Agumon', mbti_type: 'ENFP', image_path: 'character_images/digimon/agumon.png', description_kr: '천진난만한 호기심과 무한 긍정으로 가득 찬 재기발랄한 디지몬입니다. 파트너와 함께라면 어떤 위험한 도전도 설레는 모험으로 바꿔버리는 열정과 에너지의 화신입니다.', description_en: 'A bright and spirited Digimon brimming with childlike curiosity and boundless optimism. With its partner by its side, any dangerous challenge becomes an exciting adventure.' },
  ENTP: { id: 'demi_devimon', name_kr: '피코데블몬', name_en: 'Pico Devimon', mbti_type: 'ENTP', image_path: 'character_images/digimon/demi_devimon.png', description_kr: '교묘한 말재주와 기발한 계략으로 상황을 뒤흔드는 악동 디지몬입니다. 상대의 약점을 파고들어 이간질하고 변칙적인 수법으로 판을 흔들며 기존의 질서를 비트는 것을 즐깁니다.', description_en: 'A mischievous Digimon that upends situations with clever rhetoric and inventive schemes. Exploits opponents\' weaknesses, sows discord, and delights in subverting established order with unconventional methods.' },
  ESTJ: { id: 'andromon', name_kr: '안드로몬', name_en: 'Andromon', mbti_type: 'ESTJ', image_path: 'character_images/digimon/andromon.png', description_kr: '기계적 정확성과 질서를 상징하는 사이보그 디지몬입니다. 입력된 규칙과 정의에 따라 임무를 완수하며, 자신의 관리 영역 내에서 일어나는 혼란을 결코 용납하지 않는 엄격한 관리자입니다.', description_en: 'A cyborg Digimon that embodies mechanical precision and order. Completes its mission according to programmed rules and justice, never tolerating disorder within its jurisdiction.' },
  ESFJ: { id: 'garurumon', name_kr: '가루몬', name_en: 'Garurumon', mbti_type: 'ESFJ', image_path: 'character_images/digimon/garurumon.png', description_kr: '무리의 유대감과 파트너와의 신뢰를 최우선으로 하는 디지몬입니다. 날렵한 외모와 달리 내면은 매우 따뜻하며, 동료들의 기분을 살피고 팀의 화합을 위해 헌신하는 사교적인 외교관입니다.', description_en: 'A Digimon that places group bonds and trust with its partner above all else. Behind its sleek exterior lies a warm heart, always attentive to teammates\' feelings and devoted to team harmony.' },
  ENFJ: { id: 'leomon', name_kr: '레오몬', name_en: 'Leomon', mbti_type: 'ENFJ', image_path: 'character_images/digimon/leomon.png', description_kr: '정의를 위해 목숨을 바치는 숭고한 카리스마의 디지몬입니다. 자신보다 약한 디지몬들을 이끌고 보호하며, 절망적인 상황에서도 희망의 메시지를 전달하여 공동체를 고취시키는 정의로운 리더입니다.', description_en: 'A Digimon with noble charisma who gives its life for justice. Leads and protects weaker Digimon, inspiring the community with messages of hope even in the most desperate situations.' },
  ENTJ: { id: 'omnimon', name_kr: '오메가몬', name_en: 'Omnimon', mbti_type: 'ENTJ', image_path: 'character_images/digimon/omnimon.png', description_kr: '압도적인 존재감으로 전장을 지배하는 최강의 디지몬입니다. 혼란을 단숨에 잠재우고 승리라는 명확한 목표를 향해 무리를 이끄는 결단력을 가진 대담한 통솔자입니다.', description_en: 'The mightiest Digimon that dominates the battlefield with overwhelming presence. A bold commander with the decisiveness to silence chaos in an instant and lead allies toward the clear goal of victory.' },
};

const KAKAO_FRIENDS_CHARACTERS = {
  INTJ: { id: 'scarpy', name_kr: '스카피', name_en: 'Scarpy', mbti_type: 'INTJ', image_path: 'character_images/kakao_friends/scarpy.png', description_kr: '마녀의 저주로 변한 과거를 품고 조용히 셰프의 길을 걷는 캐릭터입니다. 복잡한 내면을 감춘 채 자신의 기술을 갈고닦습니다.', description_en: 'A character who quietly walks the path of a chef while carrying a cursed past. Hones skills while hiding a complex inner world.' },
  INTP: { id: 'almond', name_kr: '앙몬드', name_en: 'Almond', mbti_type: 'INTP', image_path: 'character_images/kakao_friends/almond.png', description_kr: '평소엔 늘어져 있지만 초콜릿 앞에서는 빛보다 빠른 캐릭터입니다. 특정 관심사에서 폭발적인 집중력을 발휘합니다.', description_en: 'Usually lethargic but faster than light when chocolate appears. Shows explosive focus on specific areas of interest.' },
  ENTJ: { id: 'neo', name_kr: '네오', name_en: 'Neo', mbti_type: 'ENTJ', image_path: 'character_images/kakao_friends/neo.png', description_kr: '트렌드를 직접 만들어가는 패션 리더 캐릭터입니다. 냉철하고 독립적이며 언제나 자신의 기준으로 세상을 이끕니다.', description_en: 'A fashion leader who creates trends. Cold and independent, always leads the world by its own standards.' },
  ENTP: { id: 'panda_junior', name_kr: '팬다주니어', name_en: 'Panda Junior', mbti_type: 'ENTP', image_path: 'character_images/kakao_friends/panda_junior.png', description_kr: '우주에서 떨어진 이방인 특유의 신선한 시각을 가진 캐릭터입니다. 파티라면 절대 빠지지 않으며 끊임없이 새로운 가능성을 탐색합니다.', description_en: 'A character with a fresh perspective unique to an outsider from space. Never misses a party, constantly exploring new possibilities.' },
  INFJ: { id: 'con', name_kr: '콘', name_en: 'Con', mbti_type: 'INFJ', image_path: 'character_images/kakao_friends/kakao_con.png', description_kr: '비밀스럽고 신비로운 존재입니다. 말없이 무지를 곁에서 지켜보며 깊은 통찰과 보호 본능으로 세상을 이해합니다.', description_en: 'A secretive and mysterious being. Quietly watches over Muzi, understanding the world through deep insight and protective instinct.' },
  INFP: { id: 'boksimi', name_kr: '복심이', name_en: 'Boksimi', mbti_type: 'INFP', image_path: 'character_images/kakao_friends/boksimi.png', description_kr: '자신도 불안하고 떨리지만, 타인을 치유하고 싶은 순수한 이상을 품은 캐릭터입니다. 깊은 공감과 성장으로 스스로도 치유되어 갑니다.', description_en: 'A character who trembles with anxiety yet holds a pure ideal of healing others. Through deep empathy and growth, it heals itself too.' },
  ENFJ: { id: 'jay_g', name_kr: '제이지', name_en: 'Jay-G', mbti_type: 'ENFJ', image_path: 'character_images/kakao_friends/jay_g.png', description_kr: '차갑게 보이지만 내면은 따뜻한 카리스마 넘치는 캐릭터입니다. 힙합으로 세상과 소통하며, 고독을 품은 채 타인에게 영감을 줍니다.', description_en: 'A charismatic character who appears cold but is warm inside. Connects with the world through hip-hop, inspiring others while carrying loneliness.' },
  ENFP: { id: 'muzi', name_kr: '무지', name_en: 'Muzi', mbti_type: 'ENFP', image_path: 'character_images/kakao_friends/muzi.png', description_kr: '단무지라는 비밀을 품고도 세상을 순수하게 탐험하는 캐릭터입니다. 호기심과 자유로운 감정으로 새로운 만남을 소중히 여깁니다.', description_en: 'A character who explores the world purely despite hiding the secret of being pickled radish. Treasures new encounters with curiosity and free emotion.' },
  ISTJ: { id: 'jordi', name_kr: '죠르디', name_en: 'Jordi', mbti_type: 'ISTJ', image_path: 'character_images/kakao_friends/jordi.png', description_kr: '오랜 경험을 고집하며 자격증 공부에 매진하는 캐릭터입니다. 보수적이지만 성실하고, 검증된 방식을 굳건히 믿습니다.', description_en: 'A character who insists on long experience and studies hard for certifications. Conservative but diligent, firmly trusting proven methods.' },
  ISTP: { id: 'tube', name_kr: '튜브', name_en: 'Tube', mbti_type: 'ISTP', image_path: 'character_images/kakao_friends/tube.png', description_kr: '평소엔 극도로 조용하고 감정을 억누르는 캐릭터입니다. 한계에 다다르면 미친오리로 폭발하는 예측 불가능한 내면을 숨기고 있습니다.', description_en: 'Usually extremely quiet and suppresses emotions. Hides an unpredictable interior that explodes into a \'crazy duck\' when pushed to the limit.' },
  ESTJ: { id: 'kob', name_kr: '콥', name_en: 'Kob', mbti_type: 'ESTJ', image_path: 'character_images/kakao_friends/kob.png', description_kr: '나름의 원칙과 절차를 따르는 허당 형사 캐릭터입니다. 체계를 중시하지만 실전에서는 엉뚱한 방향으로 흘러가곤 합니다.', description_en: 'A bumbling detective who follows its own principles and procedures. Values systems but tends to go hilariously off-track in practice.' },
  ESTP: { id: 'kero_veroni', name_kr: '케로&베로니', name_en: 'Kero & Veroni', mbti_type: 'ESTP', image_path: 'character_images/kakao_friends/kero_veroni.png', description_kr: '늘 붙어 다니는 장난꾸러기 쌍둥이 펭귄입니다. 충동적이고 즉흥적인 행동으로 어디서든 소동을 일으킵니다.', description_en: 'Mischievous twin penguins who are always together. Impulsive and spontaneous, causing commotion wherever they go.' },
  ISFJ: { id: 'ryan', name_kr: '라이언', name_en: 'Ryan', mbti_type: 'ISFJ', image_path: 'character_images/kakao_friends/ryan.png', description_kr: '무표정 속에 따뜻한 감정을 품은 믿음직한 캐릭터입니다. 말없이 곁에서 돌봐주며 모두의 든든한 버팀목이 되어줍니다.', description_en: 'A reliable character who hides warm emotions behind an expressionless face. Silently cares for others, becoming everyone\'s steady support.' },
  ISFP: { id: 'choonsik', name_kr: '춘식이', name_en: 'Choonsik', mbti_type: 'ISFP', image_path: 'character_images/kakao_friends/choonsik.png', description_kr: '현재 순간을 충실히 사는 고양이 캐릭터입니다. 식빵자세와 꾹꾹이로 일상을 즐기며 라이언과의 깊은 유대를 소중히 여깁니다.', description_en: 'A cat character who lives fully in the present moment. Enjoys daily life with loaf pose and kneading, cherishing a deep bond with Ryan.' },
  ESFJ: { id: 'frodo', name_kr: '프로도', name_en: 'Frodo', mbti_type: 'ESFJ', image_path: 'character_images/kakao_friends/frodo.png', description_kr: '친구들을 집에 초대해 밥을 차리는 따뜻한 캐릭터입니다. 네오에 대한 헌신적인 감정과 사교적인 성격으로 관계를 소중히 여깁니다.', description_en: 'A warm character who invites friends over and cooks for them. Values relationships deeply with devoted feelings for Neo and a social personality.' },
  ESFP: { id: 'apeach', name_kr: '어피치', name_en: 'Apeach', mbti_type: 'ESFP', image_path: 'character_images/kakao_friends/apeach.png', description_kr: '충동적이고 장난기 넘치는 에너지로 가득 찬 캐릭터입니다. 현재의 즐거움에 집중하며 주변을 소동으로 물들입니다.', description_en: 'A character full of impulsive and mischievous energy. Focuses on immediate fun and colors everything around with playful chaos.' },
};

export function getCharacterByMbtiAndSet(mbtiType, characterSet) {
  if (characterSet === 'pokemon') return POKEMON_CHARACTERS[mbtiType] || null;
  if (characterSet === 'digimon') return DIGIMON_CHARACTERS[mbtiType] || null;
  if (characterSet === 'kakao_friends') return KAKAO_FRIENDS_CHARACTERS[mbtiType] || null;
  return null;
}
